### ISSUE TITLE
Dear authors, where can I download the datasets used in this paper? I can't find it in this repository.

### ISSUE THREAD

**Issue by fywang12** [Digital-Democracies-Institute/Dimensions-of-Online-Conflict#1]
Thank you very much for your help.

**Comment by TunaObject** [comment]
hello! thanks for your interest. it should be here: https://github.com/Digital-Democracies-Institute/Dimensions-of-Online-Conflict/blob/main/training_and_test_data.zip

you should be able to unzip that file into a train and test csv. let me know if you have any issues

**Comment by fywang12** [comment]
Thank you so much.
